name: roboaugen
channels:
  - loopbio
  - pkgw-forge
  - ericmjl
  - pytorch
  - conda-forge
  - hcc
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - ffmpeg=4.0.2
  - pytorch=1.5.0
  - torchvision
  - coverage=4.5.1
  - click=6.7
  - tqdm=4.38.0
  - tensorboard
  - nvidia-apex
  - pip
  - pip:
    - opencv-python==4.0.0.21
    - torch-optimizer