name: roboaugen
channels:
  - loopbio
  - pkgw-forge
  - ericmjl
  - pytorch
  - conda-forge
  - hcc
dependencies:
  - python=3.8
  - cudatoolkit=10.1
  - ffmpeg
  - pytorch=1.7.0
  - torchvision==0.8.1
  - coverage
  - click
  - tqdm
  - tensorboard
  - nvidia-apex
  - flask
  - requests
  - simplejson
  - pip
  - pip:
    - flask-socketio==4.3.1
    - opencv-python==4.4.0.46
    - torch-optimizer
    - modern_robotics==1.1.0